name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd backend && npm ci

    - name: Run NPM Security Audit
      run: |
        npm audit --audit-level=moderate
        cd backend && npm audit --audit-level=moderate

    - name: Run Custom Security Scan
      run: |
        cd backend && npm run security:scan

    - name: Upload Security Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: backend/reports/security-report.json

    - name: Security Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('backend/reports/security-report.json')) {
            const report = JSON.parse(fs.readFileSync('backend/reports/security-report.json', 'utf8'));
            const summary = report.summary;
            
            const comment = `## 🛡️ Security Scan Results
            
            | Severity | Count |
            |----------|-------|
            | 🔴 Critical | ${summary.critical} |
            | 🟠 High | ${summary.high} |
            | 🟡 Medium | ${summary.medium} |
            | 🟢 Low | ${summary.low} |
            
            ${summary.critical > 0 || summary.high > 0 ? '⚠️ **Action Required**: Critical or high severity vulnerabilities found!' : '✅ No critical vulnerabilities detected'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
        deny-licenses: GPL-2.0, GPL-3.0 